name: Hello-World
version: '1.0'
main: me.fini69.helloworld.HelloWorld
api-version: '1.21.1'
authors: [ fini69 ]
description: A simple Hello World plugin for Paper Minecraft.

commands:
  hello:
    description: Says hello to the player
    usage: /<command>
permissions:
  helloworld.hello:
    description: Allows the player to use the hello command